### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by seltmann** [OpenEntomology/InsectBiodiversityEvolution#2]
@adeans thanks for making the effort to make your course materials open. I am teaching undergraduate entomology for the first time this summer and am finding your lectures very helpful for me to review.

**Comment by adeans** [comment]
Yaaaay!!!! You just motivated me to get the rest of the lectures up sooner rather than later! And you got me thinking about a few issues: (1) what's the best way to make these more ... generic; all have Penn State and ENT 432, but maybe we can find a way to rebrand them. (2) How should we handle authorship and acknowledgments? (3) Do we need regional variants of some handouts? Maybe you want to teach your students about seaweed flies or something western. I guess a 4th is: How should I handle lectures? They're all in Google slides. I could post links to the github wiki or make those PDFs and post here?

**Comment by seltmann** [comment]
@adeans all super good questions. I think its hard to predict how people will want to use the material. For example, since I just found out I am teaching this course, I will likely create all of the presentations in google slides, but I hope to move the materials to markdown for next year. Some of the documents, like taxonomy, are useful for my course but others are less so (I think) as I am teaching undergrads. 

It seems that you could brand the whole "concept" of open entomology lectures, like they have done for software carpentry or data carpentry. That way people have something easy to cite. A github.io page with more information about the entomology lectures as a project would be excellent as well. That way when I cite it, I have a url to point to in my citation. It would also encourage people to fork the repo rather than clone. Like I could make a fork thats "ucsb intro to entomology in markdown", and someone else could make a fork thats "insect biodiversity for undergrads at asu"...etc. It could end up as a community of courses, that vary in scope and region.

**Comment by adeans** [comment]
I planted the seeds for a github.io page - http://adeans.github.io/InsectBiodiversityEvolution

**Comment by seltmann** [comment]
yeah, that looks great!
